### ISSUE TITLE
1.11.2-1.2.0 - Internal Server Error on picking up broken block

### ISSUE THREAD

**Issue by SableDrake** [Alsender/Earthworks#13]
Server keeps running but client cannot connect again until playerdata is deleted.

Server keeps repeating this error:

[12:51:11] [Netty Epoll Server IO #14/ERROR] [FML/]: NetworkDispatcher exception
java.io.IOException: Error while writev(...): Broken pipe
	at io.netty.channel.epoll.Native.writevAddresses(Native Method) ~[Native.class:?]
	at io.netty.channel.epoll.EpollSocketChannel.writeBytesMultiple(EpollSocketChannel.java:184) ~[EpollSocketChannel.class:?]
	at io.netty.channel.epoll.EpollSocketChannel.doWriteMultiple(EpollSocketChannel.java:364) ~[EpollSocketChannel.class:?]
	at io.netty.channel.epoll.EpollSocketChannel.doWrite(EpollSocketChannel.java:317) ~[EpollSocketChannel.class:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707) [AbstractChannel$AbstractUnsafe.class:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:248) [AbstractEpollChannel$AbstractEpollUnsafe.class:?]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollOutReady(EpollSocketChannel.java:623) [EpollSocketChannel$EpollSocketUnsafe.class:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322) [EpollEventLoop.class:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [EpollEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by Alsender** [comment]
Do you happen to know what block(s) you were breaking and picking up that caused this?  I have not been able to reproduce this exactly.  I did, however, find another bug that causes the same issue you are reporting.  I did something wrong when implementing the particles in the new gabion blocks, which causes the same thing.  Were you working with these?

**Comment by SableDrake** [comment]
Yes, it was the gravel gabion block that caused it.

**Comment by Alsender** [comment]
Cool. So it's actually the particles that was doing that, cause I don't understand how those work. I just uploaded a fix to curseforge, allow a few minutes for it to be approved. Sorry about the playerdata loss :/

**Comment by SableDrake** [comment]
No worries there, we are still betatesting the modpack, nothing lost that really meant anything :)
